export const LEAD_TYPE_HEADERS: Record<string, string[]> = {
  mortgage_protection: [
    "Created At",
    "Campaign Name",
    "Lead Type",
    "Source",
    "First Name",
    "Last Name",
    "Phone",
    "Email",
    "State",
    "Age",
    "Mortgage Balance",
    "Homeowner",
    "Best Time To Call",
    "Notes",
    "Status",
    "Assigned Agent",
    "Funnel Slug",
    "Campaign ID",
    "Lead ID",
    "Duplicate",
  ],

  final_expense: [
    "Created At",
    "Campaign Name",
    "Lead Type",
    "Source",
    "First Name",
    "Last Name",
    "Phone",
    "Email",
    "State",
    "Age",
    "Coverage Amount",
    "Tobacco Use",
    "Health Notes",
    "Best Time To Call",
    "Notes",
    "Status",
    "Assigned Agent",
    "Funnel Slug",
    "Campaign ID",
    "Lead ID",
    "Duplicate",
  ],

  veteran: [
    "Created At",
    "Campaign Name",
    "Lead Type",
    "Source",
    "First Name",
    "Last Name",
    "Phone",
    "Email",
    "State",
    "Age",
    "Veteran Status",
    "Branch Of Service",
    "Coverage Amount",
    "Best Time To Call",
    "Notes",
    "Status",
    "Assigned Agent",
    "Funnel Slug",
    "Campaign ID",
    "Lead ID",
    "Duplicate",
  ],

  iul: [
    "Created At",
    "Campaign Name",
    "Lead Type",
    "Source",
    "First Name",
    "Last Name",
    "Phone",
    "Email",
    "State",
    "Age",
    "Income Range",
    "Coverage Amount",
    "Interest Type",
    "Best Time To Call",
    "Notes",
    "Status",
    "Assigned Agent",
    "Funnel Slug",
    "Campaign ID",
    "Lead ID",
    "Duplicate",
  ],

  trucker: [
    "Created At",
    "Campaign Name",
    "Lead Type",
    "Source",
    "First Name",
    "Last Name",
    "Phone",
    "Email",
    "State",
    "Age",
    "Driver Type",
    "Coverage Amount",
    "Best Time To Call",
    "Notes",
    "Status",
    "Assigned Agent",
    "Funnel Slug",
    "Campaign ID",
    "Lead ID",
    "Duplicate",
  ],
};

export const LEAD_TYPE_FOLDER_NAMES: Record<string, string> = {
  mortgage_protection: "Mortgage Protection Funnel Leads",
  final_expense: "Final Expense Funnel Leads",
  veteran: "Veteran Funnel Leads",
  iul: "IUL Funnel Leads",
  trucker: "Trucker Funnel Leads",
};

export function getLeadTypeFolderName(leadType?: string | null): string {
  const key = String(leadType || "").trim().toLowerCase();
  return LEAD_TYPE_FOLDER_NAMES[key] || (key ? `Funnel: ${key}` : "Funnel Leads");
}

export function normalizeLeadType(leadType?: string | null): string {
  return String(leadType || "").trim().toLowerCase();
}
