import styles from "@/styles/VeteranReferenceReplicas.module.css";

export type ReplicaAmount = "$40,000" | "$50,000" | "$100,000" | "$8,000";

function Icon({kind}:{kind:"medical"|"cash"|"shield"|"clock"|"family"|"calendar"|"chart"}){
  if(kind==="medical")return <svg viewBox="0 0 40 40"><path d="M13 7v12a8 8 0 0 0 16 0V7M9 7h8M25 7h8M21 28v6h9M30 31a4 4 0 1 0 0 8"/></svg>;
  if(kind==="cash"||kind==="chart")return <svg viewBox="0 0 40 40"><path d="M6 34V22h7v12M17 34V15h7v19M28 34V8h7v26M7 16l9-7 7 3 11-9M29 3h5v5"/></svg>;
  if(kind==="clock")return <svg viewBox="0 0 40 40"><circle cx="20" cy="22" r="13"/><path d="M20 22l7-6M20 22v-9M12 4l-5 5M28 4l5 5"/></svg>;
  if(kind==="family")return <svg viewBox="0 0 40 40"><circle cx="13" cy="14" r="5"/><circle cx="27" cy="14" r="5"/><circle cx="20" cy="24" r="4"/><path d="M4 34c1-8 5-12 9-12s7 3 7 7M36 34c-1-8-5-12-9-12s-7 3-7 7M12 38c1-7 4-10 8-10s7 3 8 10"/></svg>;
  if(kind==="calendar")return <svg viewBox="0 0 40 40"><rect x="7" y="9" width="26" height="25" rx="2"/><path d="M13 4v10M27 4v10M7 17h26M14 25l4 4 8-9"/></svg>;
  return <svg viewBox="0 0 40 40"><path d="M20 4l14 6v10c0 9-6 14-14 17C12 34 6 29 6 20V10zM14 20l4 4 9-10"/></svg>;
}

const Ages=()=> <div className={styles.ageBoxes}><span>50–60</span><span>61–70</span><span>71–80</span><span>81+</span></div>;

function Replica01({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r01}`} data-reference-replica="01"><div className={styles.stars}/><h1>VETERANS</h1><h2>WHOLE LIFE<br/>INSURANCE</h2><div className={styles.rule}/><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.goldBar}>NO 2-YEAR WAIT</div><div className={styles.iconRow}><div><Icon kind="medical"/><b>NO MEDICAL<br/>EXAM</b></div><div><Icon kind="chart"/><b>CASH VALUE<br/>GROWS</b></div><div><Icon kind="shield"/><b>PROTECT<br/>YOUR FAMILY</b></div></div><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica02({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r02}`} data-reference-replica="02"><div className={styles.flagWash}/><h1>MILITARY</h1><h2>WHOLE LIFE</h2><h3>PROTECT YOUR FAMILY.<br/>LEAVE A LEGACY.</h3><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.checks}><b>✓ <span>NO MEDICAL EXAM</span></b><b>✓ <span>NO 2-YEAR WAIT</span></b><b>✓ <span>ACCEPTANCE UP TO AGE 85</span></b></div><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica03(){return <div className={`${styles.replica} ${styles.r03}`} data-reference-replica="03"><h1>VETERANS</h1><h2>DON’T LEAVE YOUR FAMILY<br/>WITH THE BILL</h2><section className={styles.problem}><b>FUNERAL COSTS<br/>AVERAGE OVER</b><strong>$8,000</strong></section><h3>WHOLE LIFE INSURANCE CAN HELP</h3><div className={styles.iconRow}><div><Icon kind="shield"/><b>Lock In<br/>Your Rate</b></div><div><Icon kind="chart"/><b>Cash Value<br/>Grows</b></div><div><Icon kind="family"/><b>Peace of Mind<br/>for Your Family</b></div></div><div className={styles.goldCta}>SEE YOUR OPTIONS&nbsp; ›</div></div>}
function Replica04({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r04}`} data-reference-replica="04"><h1>VETERANS</h1><h2>PRIVATE COVERAGE<br/><span>THAT PROTECTS</span></h2><div className={styles.starRule}>★ ★ ★</div><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.iconRow}><div><Icon kind="medical"/><b>NO MEDICAL<br/>EXAM</b></div><div><Icon kind="clock"/><b>NO 2-YEAR<br/>WAIT</b></div><div><Icon kind="shield"/><b>ACCEPTANCE<br/>UP TO AGE 85</b></div></div><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica05({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r05}`} data-reference-replica="05"><h1>✦ VETERANS ✦</h1><h2>SECURE TODAY<br/>PROTECT TOMORROW</h2><div className={styles.product}>WHOLE LIFE INSURANCE</div><div className={styles.iconRow}><div><Icon kind="shield"/><b>LIFETIME<br/>COVERAGE</b></div><div><Icon kind="cash"/><b>CASH VALUE<br/>GROWS</b></div><div><Icon kind="calendar"/><b>TAX-DEFERRED<br/>GROWTH</b></div></div><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica06({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r06}`} data-reference-replica="06"><h1>VETERANS</h1><h2>WE THANK YOU.</h2><h3>NOW LET US HELP YOU<br/>PROTECT YOUR FAMILY.</h3><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.iconRow}><div><Icon kind="medical"/><b>NO MEDICAL<br/>EXAM</b></div><div><Icon kind="clock"/><b>NO 2-YEAR<br/>WAIT</b></div><div><Icon kind="shield"/><b>ACCEPTANCE<br/>UP TO AGE 85</b></div></div><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica07({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r07}`} data-reference-replica="07"><div className={styles.vetImage}/><div className={styles.vetVeil}/><section className={styles.copy}><h1>YOU SERVED.<br/>NOW PROTECT<br/>WHAT MATTERS.</h1><div className={styles.redRule}>★ ★ ★</div><h2>WHOLE LIFE INSURANCE</h2><div className={styles.checks}><b>✓ <span>NO MEDICAL EXAM</span></b><b>✓ <span>NO 2-YEAR WAIT</span></b><b>✓ <span>CASH VALUE GROWS</span></b><b>✓ <span>PROTECT YOUR FAMILY</span></b></div></section><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica08({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r08}`} data-reference-replica="08"><div className={styles.stars}/><h1>MILITARY FAMILIES</h1><h2>DESERVE FINANCIAL<br/>PROTECTION</h2><h3>WHOLE LIFE INSURANCE</h3><div className={styles.iconRow}><div><Icon kind="family"/><b>PROTECT<br/>YOUR FAMILY</b></div><div><Icon kind="shield"/><b>LIFETIME<br/>COVERAGE</b></div><div><Icon kind="chart"/><b>BUILD CASH<br/>VALUE</b></div></div><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica09({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r09}`} data-reference-replica="09"><h1>VETERANS</h1><h2>LIFE INSURANCE</h2><h3>PEACE OF MIND FOR YOU.<br/>SECURITY FOR THEM.</h3><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.iconRow}><div><Icon kind="medical"/><b>NO MEDICAL EXAM</b></div><div><Icon kind="clock"/><b>NO 2-YEAR<br/>WAIT</b></div><div><Icon kind="shield"/><b>ACCEPTANCE<br/>UP TO AGE 85</b></div></div><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica10({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r10}`} data-reference-replica="10"><h1>VETERANS</h1><h2>WHOLE LIFE INSURANCE</h2><h3>BUILT FOR YOU.<br/>BACKED BY US.</h3><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.iconRow}><div><Icon kind="shield"/><b>LIFETIME<br/>COVERAGE</b></div><div><Icon kind="chart"/><b>CASH VALUE<br/>GROWS</b></div><div><Icon kind="family"/><b>PROTECT<br/>YOUR FAMILY</b></div></div><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica11({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r11}`} data-reference-replica="11"><h1>SERVE WITH HONOR.<br/>PROTECT WITH PURPOSE.</h1><div className={styles.rule}/><h2>WHOLE LIFE INSURANCE</h2><div className={styles.checks}><b>✓ <span>NO MEDICAL EXAM</span></b><b>✓ <span>NO 2-YEAR WAIT</span></b><b>✓ <span>ACCEPTANCE UP TO AGE 85</span></b></div><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}
function Replica12({amount}:{amount:ReplicaAmount}){return <div className={`${styles.replica} ${styles.r12}`} data-reference-replica="12"><h1>MILITARY STRONG</h1><h2>FUTURE SECURE</h2><h3>WHOLE LIFE INSURANCE</h3><div className={styles.iconRow}><div><Icon kind="family"/><b>PROTECT YOUR<br/>FAMILY</b></div><div><Icon kind="cash"/><b>BUILD CASH<br/>VALUE</b></div><div><Icon kind="shield"/><b>LEAVE A<br/>LEGACY</b></div></div><section className={styles.amount}><small>COVERAGE OPTIONS UP TO</small><strong>{amount}</strong></section><div className={styles.age}><b>TAP YOUR AGE:</b><Ages/></div></div>}

export function VeteranReferenceReplicaCard({tile,amount}:{tile:number;amount:ReplicaAmount}){
  if(tile===1)return <Replica01 amount={amount}/>;if(tile===2)return <Replica02 amount={amount}/>;if(tile===3)return <Replica03/>;if(tile===4)return <Replica04 amount={amount}/>;if(tile===5)return <Replica05 amount={amount}/>;if(tile===6)return <Replica06 amount={amount}/>;if(tile===7)return <Replica07 amount={amount}/>;if(tile===8)return <Replica08 amount={amount}/>;if(tile===9)return <Replica09 amount={amount}/>;if(tile===10)return <Replica10 amount={amount}/>;if(tile===11)return <Replica11 amount={amount}/>;return <Replica12 amount={amount}/>;
}
