// models/DOIAgent.ts
// Canonical record for every scraped DOI agent before enrichment/verification.
import mongoose, { Schema, InferSchemaType, models, model } from "mongoose";

const DOIAgentSchema = new Schema(
  {
    firstName: { type: String, default: "" },
    lastName: { type: String, default: "" },
    fullName: { type: String, default: "" },
    state: { type: String, index: true },
    city: { type: String, default: "" },
    licenseNumber: { type: String, default: "", index: true },
    licenseType: { type: String, default: "" },
    licenseStatus: { type: String, default: "" },
    agencyName: { type: String, default: "" },
    agencyWebsite: { type: String, default: "" },
    agencyDomain: { type: String, default: "", index: true },
    domainTrustLevel: {
      type: String,
      enum: [
        "",
        "trusted_business",
        "generic_directory",
        "government",
        "social",
        "low_trust",
        "blacklisted",
      ],
      default: "",
      index: true,
    },
    phone: { type: String, default: "" },
    email: { type: String, default: "" },
    website: { type: String, default: "" },
    address: { type: String, default: "" },
    businessAddress: { type: String, default: "" },
    zip: { type: String, default: "" },
    npn: { type: String, default: "", index: true },
    identitySource: { type: String, default: "" },
    identityUpdatedAt: { type: Date },
    domicileState: { type: String, default: "" },
    residentFlag: { type: String, default: "" },
    designatedHomeState: { type: String, default: "" },
    licenseIssueDate: { type: String, default: "" },
    licenseEffectiveDate: { type: String, default: "" },
    licenseExpirationDate: { type: String, default: "" },
    licenseStatusDate: { type: String, default: "" },
    linesOfAuthority: { type: [String], default: [] },
    isLicenseActive: { type: Boolean, default: false },
    isLicenseCurrent: { type: Boolean, default: false },
    isRecentlyRenewed: { type: Boolean, default: false },
    isRecentlyLicensed: { type: Boolean, default: false },
    isFreshLicenseLead: { type: Boolean, default: false },
    freshnessBucket: { type: String, default: "" },
    freshnessEvaluatedAt: { type: Date },
    sbsLastEnrichedAt: { type: Date },
    sbsLookupAttempts: { type: Number, default: 0 },
    sbsLastLookupAt: { type: Date },
    sbsLastLookupError: { type: String, default: "" },
    enrichmentStatus: {
      type: String,
      enum: ["pending", "enriched", "failed"],
      default: "pending",
      index: true,
    },
    confidenceScore: { type: Number, default: 0 },
    lastCheckedAt: { type: Date },
    source: { type: String, default: "" },
    attempts: { type: Number, default: 0 },
    lastAttemptAt: { type: Date },
    pipelineStage: {
      type: String,
      enum: [
        "pending",
        "discovery",
        "domain",
        "patterns",
        "email",
        "ready",
        "verification",
        "promoted",
        "failed",
      ],
      default: "pending",
      index: true,
    },
    notes: { type: String, default: "" },
    stuckReason: { type: String, default: "" },
    rejectionReasons: { type: [String], default: [] },
    lastRejectionReason: { type: String, default: "" },
    reviewNeeded: { type: Boolean, default: false },
    searchQueries: { type: [String], default: [] },
    searchResultCount: { type: Number, default: 0 },
    lastSearchAt: { type: Date },
    lastParsedAt: { type: Date },
    lastIdentityResolveAt: { type: Date },
    identityScore: { type: Number, default: 0 },
    identityConfidence: {
      type: String,
      enum: ["", "low", "medium", "high"],
      default: "",
    },
    identityReasons: { type: [String], default: [] },
    selectedDomainAt: { type: Date },
    evidenceSummary: { type: String, default: "" },
    lastEnrichedAt: { type: Date },
    leadScore: { type: Number, default: 0 },
    leadGrade: {
      type: String,
      enum: ["", "A", "B", "C", "D"],
      default: "",
    },
    engagementScore: { type: Number, default: 0 },
    deliverabilityScore: { type: Number, default: 0 },
    yearsLicensed: { type: Number, default: 0 },
    multiStateLicensed: { type: Boolean, default: false },
    emailDiscoveryMode: { type: String, default: "" },
  },
  { timestamps: true }
);

DOIAgentSchema.index(
  { state: 1, licenseNumber: 1 },
  { unique: true, sparse: true }
);
DOIAgentSchema.index({ npn: 1 }, { unique: true, sparse: true });

export type DOIAgent = InferSchemaType<typeof DOIAgentSchema>;
export default (models.DOIAgent as mongoose.Model<DOIAgent>) ||
  model<DOIAgent>("DOIAgent", DOIAgentSchema);
